version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/quote-api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on: 
      - quote-api

  quote-api:
    build: .
    volumes:
      - .:/var/www/quote-api
    ports:
      - 9000:9000